version: '3.7'
services:
  web:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - mynetwork

  php:
    image: php:7.4-fpm
    container_name: php_container
    volumes:
      - ./web:/var/www/html
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Lifei23
      MYSQL_DATABASE: target_db
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
